---
title: "My Map Presentation"
author: "Rama Tripathy"
date: "May 31, 2017"
output:
  html_document: default
  pdf_document: default
---

## Statefarm Office Map   
```{r, comment = "", eval=FALSE}
library(leaflet)
my_map <- leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat=40.4614, lng = -88.9530)
my_map
```
### Marker with name popup  
```{r, comment = "", eval=FALSE}
library(leaflet)
my_map <- leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat=40.4614, lng = -88.9530,
             popup="Statefarm Office")
my_map
```
### Adding Many Markers
```{r, comment = "", eval=FALSE}
library(leaflet)
set.seed(123)
df <- data.frame(lat = runif(20, min = 40.4, max = 40.5),
                 lng = runif(20, min = -88.9, max = -88.8))
df %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers()

```
### Making Circle Markers  
```{r, comment = "", eval=FALSE}
library(leaflet)
set.seed(123)
df <- data.frame(lat = runif(20, min = 40.4, max = 40.5),
                 lng = runif(20, min = -88.9, max = -88.8))
df %>% 
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers()
```
###  Adding Legends   
```{r}
library(leaflet)
df <- data.frame(lat = runif(20, min = 40.4, max = 40.5),
                 lng = runif(20, min = -88.9, max = -88.8),
                 col = sample(c("red", "blue", "green"), 20, replace = TRUE),
                 stringsAsFactors = FALSE)

df %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(color = df$col) %>%
  addLegend(labels = LETTERS[1:3], colors = c("blue", "red", "green"))
```
###  Conclusion  
For the webpage refer to this link: http://rpubs.com/triparc/Leaflet

